name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Generate Changelog
        id: changelog
        run: deno .github/actions/changelog.ts
        with:
          token: ${{ github.token }}


      - uses: actions/cache@v2
        with:
          path: |
            libs
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: deps-${{ hashFiles('dependencies.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            deps-
      - name: Run unit tests and build JAR
        run: ./gradlew buildPlugin precompileZip allInOneJar

      - name: upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: "Pre-release build ${{github.run_number}}"
          body: ${{steps.changelog.outputs.releaseBody}}
          files: |
            build/distributions/*
            build/libs/*
